name: now-deploy

on: push

jobs:
  now-dev:
    strategy:
      matrix:
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
        node: ['12.x']
        deno: ['0.31.0']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: now-dev-${{ matrix.os }}-node${{ matrix.node }}-deno${{ matrix.deno }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Setup deno
        uses: denolib/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn build
